### ISSUE TITLE
EAF System Monitor Fails to Start

### ISSUE THREAD

**Issue by Trent-Fellbootman** [emacs-eaf/eaf-system-monitor#25]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.

```
qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)
[JavaScript console]: TypeError: Cannot read properties of undefined (reading 'percent')
Traceback (most recent call last):
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 56, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/app/system-monitor/buffer.py", line 68, in update_process_info
    info["cmdline"] = " ".join(info["cmdline"])
TypeError: can only join an iterable
[JavaScript console]: TypeError: Cannot read properties of undefined (reading 'percent')
Traceback (most recent call last):
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 56, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/app/system-monitor/buffer.py", line 68, in update_process_info
    info["cmdline"] = " ".join(info["cmdline"])
TypeError: can only join an iterable
Traceback (most recent call last):
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 56, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/app/system-monitor/buffer.py", line 68, in update_process_info
    info["cmdline"] = " ".join(info["cmdline"])
TypeError: can only join an iterable
Traceback (most recent call last):
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 56, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/app/system-monitor/buffer.py", line 68, in update_process_info
    info["cmdline"] = " ".join(info["cmdline"])
TypeError: can only join an iterable
Traceback (most recent call last):
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 56, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/app/system-monitor/buffer.py", line 68, in update_process_info
    info["cmdline"] = " ".join(info["cmdline"])
TypeError: can only join an iterable
Traceback (most recent call last):
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 56, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/app/system-monitor/buffer.py", line 68, in update_process_info
    info["cmdline"] = " ".join(info["cmdline"])
TypeError: can only join an iterable
Traceback (most recent call last):
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 56, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/app/system-monitor/buffer.py", line 68, in update_process_info
    info["cmdline"] = " ".join(info["cmdline"])
TypeError: can only join an iterable
Traceback (most recent call last):
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/core/utils.py", line 56, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/trent/.emacs.d/site-lisp/emacs-application-framework/app/system-monitor/buffer.py", line 68, in update_process_info
    info["cmdline"] = " ".join(info["cmdline"])
TypeError: can only join an iterable
...(the above error repeats)
```

**Describe the bug**
EAF system monitor failed to start and nothing appears.

**To Reproduce**
Install EAF system monitor using the installation script provided by `eaf` and `<M-x>eaf-open-system-monitor<ret>`

**Expected behavior**
EAF system monitor opens up correctly.

**Versions (please complete the following info):**
 - Distro and DE/WM:
 ```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```
 - Versions of Dependencies:
 - M-x emacs-version: GNU Emacs 27.1

**Screenshots**

**Additional context**

**Comment by manateelazycat** [comment]
Please try ```cd emacs-application-framework/app/system-monitor ; rm -rf ./node_modules ; npm install ; npm run build```

to rebuild system monitor agian.

I have rebuild it, works fine.

![Uploading 截图 2023-12-18 11-50-16.png…]()
